Repository castcle/castcle-trigger, pull requests merged in 2022-03, with the labels that each got.

#271 Etl/user engagement stats
  modules/etl_user_engagement_stats/__init__.py
  modules/etl_user_engagement_stats/etl_user_engagement_stats.py
  modules/utils/mongo_connector.py
  user_engagement_stats_update.py
Labels: documentation

#273 Fraud detection/model training
  .gitignore
  fraud_detection_model_trainer.py
  modules/fraud_detection_model_training/__init__.py
  modules/fraud_detection_model_training/fraud_detection_model_training.py
  modules/fraud_detection_model_training/models/__init__.py
  modules/fraud_detection_model_training/models/one_class_classifier_based_on_pca.py
  requirements.txt
Labels: enhancement

#277 Model/user engagement trainer
  modules/user_classify/__init__.py
  modules/user_classify/kmeans.py
  modules/user_classify/user_classify_trainer.py
  serverless.yml
  user_classify_trainer.py
Labels: enhancement

#278 fix: [ERROR] ModuleNotFoundError: No module named 'kmeans' Traceback …
  modules/user_classify/user_classify_trainer.py
Labels: bug

#279 fix: calling Class
  modules/user_classify/user_classify_trainer.py
Labels: bug

#280 remove commends
  modules/user_classify/user_classify_trainer.py
Labels: documentation

#284 Model/user engagement trainer predict
  modules/user_classify/user_classify_trainer_pred.py
  user_classify_trainer.py
Labels: enhancement

#299 add: exception
  user_classify_trainer.py
Labels: bug

#300 fix: not enough data for user classify
  user_classify_trainer.py
Labels: documentation

#301 add more semantic logs
  user_classify_trainer.py
Labels: documentation

#302 Logging
  user_classify_trainer.py
Labels: documentation

#304 Change lambda memory
  serverless.yml
Labels: bug

#306 Feed performance/time windows
  modules/feed_performance_monitor/feed_performance_monitor.py
  serverless.yml
Labels: documentation

#307 change time string to datetime format
  modules/feed_performance_monitor/feed_performance_monitor.py
Labels: documentation

#308 Fix feed performance
  modules/feed_performance_monitor/feed_performance_monitor.py
  serverless.yml
Labels: bug

#309 Update serverless.yml
  serverless.yml
Labels: bug

#310 fix feeditems today-1
  modules/feed_performance_monitor/feed_performance_monitor.py
Labels: documentation

#311 Fix feedperformance memory
  modules/feed_performance_monitor/feed_performance_monitor.py
Labels: bug, enhancement

#312 fix ZeroDivided score
  modules/feed_performance_monitor/feed_performance_monitor.py
Labels: bug

#313 Fix: DividedZero
  modules/feed_performance_monitor/feed_performance_monitor.py
Labels: bug

#324 feat: updatedAt to contentinfo
  modules/topic_classify/topic_classification.py
Labels: documentation

#325 hotfix/ updatedAt in contentinfo
  modules/topic_classify/topic_classification.py
Labels: documentation

#326 Staging -> Main
  modules/topic_classify/topic_classification.py
Labels: documentation

#327 feat: Remove $lookup in personalize content trainer (WorkAround)
  modules/personalized_content/personalize_content_trainer.py
Labels: documentation

#328 Remove $Lookup
  modules/personalized_content/personalize_content_trainer.py
Labels: documentation

#334 Revert "feat: Remove $lookup in personalize content trainer (WorkAround)"
  modules/personalized_content/personalize_content_trainer.py
Labels: bug

#335 Revert $Lookup personalize content trainer
  modules/personalized_content/personalize_content_trainer.py
Labels: bug
